"""empty message

Revision ID: d4734c9c8243
Revises: 2807edd385a2
Create Date: 2022-02-23 08:27:36.087587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4734c9c8243'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'created_at')
    op.drop_table('role')
    # ### end Alembic commands ###
